all:
  hosts:
    sirm01:
      ansible_host: 10.11.12.2
    sirm02:
      ansible_host: 10.11.12.3

  children:
    webservers:
      hosts:
        sirm01:
        sirm02:
      vars:
        http_port: 8081

    dbservers:
      hosts:
        sirm01:
      vars:
        db_port: 3306